
[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "20"

# API endpoint redirection
[[redirects]]
  from = "/api/upload-file"
  to = "/.netlify/functions/upload-file"
  status = 200

[[redirects]]
  from = "/api/*"
  to = "/api/:splat"
  status = 200

# SPA fallback
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Header configurations for uploads
[[headers]]
  for = "/uploads/*"
  [headers.values]
    Content-Type = "application/octet-stream"
    Content-Disposition = "attachment"
    Cache-Control = "public, max-age=86400"
    Access-Control-Allow-Origin = "*"

[[headers]]
  for = "/lovable-uploads/*"
  [headers.values]
    Cache-Control = "public, max-age=86400"
    Access-Control-Allow-Origin = "*"

# Add headers for API endpoints to handle CORS properly
[[headers]]
  for = "/api/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
    Access-Control-Allow-Headers = "Origin, X-Requested-With, Content-Type, Accept, Authorization"

# Service worker headers
[[headers]]
  for = "/api/upload-file.js"
  [headers.values]
    Content-Type = "application/javascript"
    Service-Worker-Allowed = "/"
