// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hjjtsbkxxvygpurfhlub.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhqanRzYmt4eHZ5Z3B1cmZobHViIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzcxNzYxNjAsImV4cCI6MjA1Mjc1MjE2MH0.HOIhZDOZ6jZDMq2aKdiH5AjhDKQI3e1x21o7sLpqyKk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);